name: Validate terraform fmt and validate

on:
  pull_request:
    branches: [main, master]

permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: Check terraform fmt
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Fetch changed files
        id: pr_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "space-delimited"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Run terraform fmt on changed files
        run: |
          set +e
          echo "CHECK_STATUS=0" >> $GITHUB_ENV
          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
            if [[ $changed_file == *.tf ]]; then
              terraform fmt -check $changed_file || CHECK_STATUS=1
            fi
          done
      - name: Exit with fmt status
        run: exit $CHECK_STATUS

  validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
